StellarCN/py-stellar-base

- stellar_base/sample.py
Don't error anymore and runs, though not sure if correctly
> Fixes naming in sample.py

- tests/test_cases.py
Use with nosetests. Based on problems in issues #7 and #12.
P.S. Most of other tests are failing.
> Add 6 tests

- stellar_base/horizon.py
> Fix requests.get() in horizon

- .travis.yml
> Edit travis for nosetests

- stellar_base/asset.py
- stellar_base/operation.py
- stellar_base/utils.py
- tests/test_envelope.py
> fix createPassiveOffer, manageOffer, pathPayment

- stellar_base/horizon.py
> Fix horizon that skipped params in request.post

- stellar_base/asset.py
- stellar_base/operation.py
- stellar_base/transaction.py
- stellar_base/transaction_envelope.py
- stellar_base/utils.py
- tests/test_envelope.py
also:
* change offerId to offer_id in operation.py
* change seqNum to sequence in Transaction.py
> add from_xdr() for TransactionEnvelope

- tests/test_envelope.py
Present in 4e23ea6 and fixed in 8dbf82d.
> Add tests for last-op-replaces-all-ops bug

- stellar_base/asset.py
- stellar_base/operation.py
- stellar_base/transaction.py
- stellar_base/transaction_envelope.py
- stellar_base/utils.py
- tests/test_envelope.py
- tests/test_horizon.py
> Horizontest

- stellar_base/builder.py
See: https://github.com/StellarCN/py-stellar-base/blob/master/stellar_base/address.py#L25
> make livenet option for stellar_base.Builder consistent with stellar_base.Address

- README.md
- stellar_base/builder.py
- stellar_base/horizon.py
- tests/test_builder.py
- tests/test_horizon.py
1. fix a bug
```
>>> from stellar_base.builder import Builder
>>> seed = "SCVLSUGYEAUC4MVWJORB63JBMY2CEX6ATTJ5MXTENGD3IELUQF4F6HUB"
>>> builder = Builder(secret=seed)
Traceback (most recent call last):
File "<input>", line 1, in <module>
builder = Builder(secret=seed)
File "/home/dev/py-stellar-base/stellar_base/builder.py", line 35, in __in
it__
if network.upper() != 'PUBLIC':
AttributeError: 'NoneType' object has no attribute 'upper'
```
2. get assets information from horizon.
URL: https://horizon.stellar.org/assets
3. fix the mistake in the example.
4. handle tx_bad_seq in tests, the code can pass traivs test now.
> some fixes.

- MANIFEST.in
- stellar_base/utils.py
> fix: the wordlist should be included

- stellar_base/builder.py
- tests/test_builder.py
I think this change makes the transaction builder nicer to use (and closer to the official libraries)
> Add method chaining to transaction builder

- appveyor.yml
> test on Windows

- README.md
- stellar_base/keypair.py
- stellar_base/utils.py
- tests/test_keypair.py
> sep-0005 support

- stellar_base/builder.py
Proposing to add this comment.
> Preauth doc

- docs/quickstart.rst
Using "_gen_xdr_" intead of "_to_xdr_" as it's no longer available.
> Fix method name

- stellar_base/builder.py
- stellar_base/horizon.py
- stellar_base/operation.py
- stellar_base/transaction.py
When not using the SSEClient, the sse parameter shouldn't be set.
> Remove 'sse' in params

- examples/create_keypair.py
- stellar_base/__init__.py
- stellar_base/exceptions.py
- stellar_base/keypair.py
- stellar_base/utils.py
- tests/test_keypair.py
- tests/test_utils.py
Together with some small refactoring the the class Keypair and StellarMnemonic.
> Throw more clear errors in Keypair init and sign

- README.rst
> fix example

- stellar_base/address.py
Can we add this? I need it for an internal check.
> Add inflation_destination to address object.

- stellar_base/memo.py
- stellar_base/transaction.py
- tests/test_envelope.py
- tests/test_memo.py
Hi,
This PR is a refactoring of the constructors of memo classes into factory. The bijection between the memo object and the corresponding xdr object is also tested.
> wrap memo classes construction as factory build 

- stellar_base/address.py
- stellar_base/asset.py
- stellar_base/builder.py
- stellar_base/exceptions.py
- stellar_base/federation.py
- stellar_base/horizon.py
- stellar_base/keypair.py
- stellar_base/memo.py
- stellar_base/operation.py
- stellar_base/transaction.py
- stellar_base/transaction_envelope.py
- stellar_base/utils.py
- tests/test_asset.py
- tests/test_federation.py
- tests/test_keypair.py
- tests/test_memo.py
- tests/test_operation.py
- tests/test_utils.py
> more specific exceptions

- stellar_base/builder.py
- stellar_base/horizon.py
> Horizon 0.17.0

- stellar_base/builder.py
- stellar_base/keypair.py
- tests/test_builder.py
> feat: Support for SEP 10 challenge transaction.

- docs/en/api.rst
- docs/zh_CN/api.rst
- stellar_sdk/call_builder/__init__.py
- stellar_sdk/call_builder/strict_receive_paths_call_builder.py
- stellar_sdk/call_builder/strict_send_paths_call_builder.py
- stellar_sdk/server.py
- tests/call_builder/test_root_call_builder.py
- tests/call_builder/test_strict_receive_paths_call_builder.py
- tests/call_builder/test_strict_send_paths_call_builder.py
- tests/test_server.py
> feat: Add support for /paths/strict-send

- docs/en/api.rst
- docs/zh_CN/api.rst
- examples/transaction_challenge.py
- stellar_sdk/account.py
- stellar_sdk/sep/ed25519_public_key_signer.py
- stellar_sdk/sep/stellar_web_authentication.py
- stellar_sdk/server.py
- tests/sep/test_stellar_web_authentication.py
- tests/test_account.py
- tests/test_server.py
> update challenge tx helpers for SEP-0010 v1.3.0.

- examples/transaction_challenge.py
- stellar_sdk/sep/stellar_web_authentication.py
- tests/sep/test_stellar_web_authentication.py
#252, I didn't add `Strkey.decode_version_byte here`, will add it later.
> fix: fix bug in SEP-0010.

- stellar_sdk/account.py
- stellar_sdk/exceptions.py
- stellar_sdk/fee_bump_transaction.py
- stellar_sdk/keypair.py
- stellar_sdk/operation/account_merge.py
- stellar_sdk/operation/operation.py
- stellar_sdk/operation/path_payment_strict_receive.py
- stellar_sdk/operation/path_payment_strict_send.py
- stellar_sdk/operation/payment.py
- stellar_sdk/operation/utils.py
- stellar_sdk/server.py
- stellar_sdk/strkey.py
- stellar_sdk/transaction.py
- stellar_sdk/transaction_builder.py
- stellar_sdk/utils.py
- tests/test_fee_bump_transaction.py
- tests/test_memo.py
- tests/test_operation.py
- tests/test_strkey.py
- tests/test_time_bounds.py
- tests/test_transaction.py
- tests/test_utils.py
> feat: add support for SEP-0023 (Augmented strkey format for multiplexed accounts)

- stellar_sdk/call_builder/payments_call_builder.py
- tests/call_builder/test_payments_call_builder.py
> feat: add `stellar_sdk.call_builder.PaymentsCallBuilder.join`

- stellar_sdk/transaction.py
- stellar_sdk/transaction_builder.py
- tests/test_transaction_builder.py
- tests/test_transaction_envelope.py
> refactor: generate V1 transactions by default

- stellar_sdk/helpers.py
- stellar_sdk/sep/stellar_uri.py
- stellar_sdk/utils.py
- tests/sep/test_stellar_uri.py
> feat: add support for parsing Stellar URI (SEP-0007).

- stellar_sdk/sep/stellar_web_authentication.py
- tests/sep/test_stellar_web_authentication.py
Ref https://github.com/stellar/stellar-protocol/pull/708
> feat: add support for SEP-0010 2.0.0.

- stellar_sdk/sep/stellar_web_authentication.py
- tests/sep/test_stellar_web_authentication.py
> feat: add support for SEP-10 v2.1.0.

- stellar_sdk/account.py
Made grammatical changes to add clarity around Account object. No code changes, only comments to enhance documentation.
> Update account.py Comments

- requirements.txt
> chore(deps): bump pynacl from 1.3.0 to 1.4.0

- stellar_sdk/sep/stellar_web_authentication.py
- tests/sep/test_stellar_web_authentication.py
https://github.com/stellar/js-stellar-sdk/pull/613#discussion_r560066720
> fix: SEP-10, removed non-null constraint for manageData op values

- setup.py
https://mypy.readthedocs.io/en/stable/installed_packages.html#making-pep-561-compatible-packages
> feat: added a `py.typed` file so that mypy will know to use our type annotations.

- stellar_sdk/asset.py
> asset.py: make native classmethod

- examples/manage_sell_offer.py
Hey, 
i noticed that there isn't a manage sell offer example. 
I tried to create one with some explanation. 
Hope it will help someone.
> added: manage sell offer example

- stellar_sdk/call_builder/operations_call_builder.py
- stellar_sdk/call_builder/transactions_call_builder.py
- tests/call_builder/test_operations_call_builder.py
- tests/call_builder/test_transactions_call_builder.py
> feat: add support for claimable balances endpoints.

- stellar_sdk/muxed_account.py
- tests/test_muxed_account.py
> refactor: make MuxedAccount.account_muxed returns Optional[str]

- stellar_sdk/sep/stellar_web_authentication.py
- tests/sep/test_stellar_web_authentication.py
> feat: SEP-10, adds a 5 minute grace period to read_challenge_transaction min_time constraint

- stellar_sdk/call_builder/trades_call_builder.py
- tests/call_builder/test_trades_call_builder.py
> feat: add /liquidity_pools/:pool_id/trades endpoint support.

- stellar_sdk/sep/stellar_web_authentication.py
- tests/sep/test_stellar_web_authentication.py
`MuxedAccount.account_muxed` first checks if `ENABLE_SEP_0023` is set to true and raises a `FeatureNotEnabledError` if it is not, even if `MuxedAccount.account_muxed` is `None` (meaning, its a `G...` address).
These changes ensure `FeatureNotEnabledError` is caught and determines the source is actually a muxed account. If it is, we return an `InvalidSep10ChallengeError`, otherwise we simply fetch the `G...` address as expected.
> SEP-10: Fix case where muxed accounts are not enabled

- stellar_sdk/asset.py
This allows users to put Assets in set()
> Make Asset hashable

- stellar_sdk/xdr/__init__.py
- stellar_sdk/xdr/ledger_header.py
> fix: xdr, fixed-length arrays pack/unpack should include length

- stellar_sdk/server.py
- stellar_sdk/server_async.py
> docs: correct the horizon address of the public network

- .github/workflows/continuous-integration-workflow.yml
- README.rst
- docs/en/index.rst
- docs/zh_CN/index.rst
- poetry.lock
- pyproject.toml
> chore!: drop support for Python 3.6

- poetry.lock
- pyproject.toml
- stellar_sdk/client/aiohttp_client.py
- stellar_sdk/client/base_async_client.py
- stellar_sdk/client/base_sync_client.py
- stellar_sdk/client/requests_client.py
- stellar_sdk/client/simple_requests_client.py
- stellar_sdk/soroban/__init__.py
- stellar_sdk/soroban/exceptions.py
- stellar_sdk/soroban/jsonrpc.py
- stellar_sdk/soroban/server.py
- stellar_sdk/soroban/soroban_rpc.py
```python
import time
from stellar_sdk import *
from stellar_sdk import xdr as stellar_xdr
from stellar_sdk.soroban import SorobanServer
kp1 = Keypair.from_secret("SAAPYAPTTRZMCUZFPG3G66V4ZMHTK4TWA6NS7U4F7Z3IMUD52EK4DDEV")
soroban_server = SorobanServer("http://127.0.0.1:8000/soroban/rpc")
acc = soroban_server.get_account(kp1.public_key)
source = Account(kp1.public_key, acc.sequence)
op1 = InvokeHostFunction(
contract_id="ca08ea2c19bd47d9e04de0cc86e1440866f6c7f8634095872c38000e1a7cbcd9",
method="hello",
params=[stellar_xdr.SCVal(type=stellar_xdr.SCValType.SCV_SYMBOL,
sym=stellar_xdr.SCSymbol(sc_symbol="world".encode('utf-8')))],
footprint=stellar_xdr.LedgerFootprint([], []),
source=kp1.public_key
)
tx1 = TransactionBuilder(source, network_passphrase='Standalone Network ; February …
```
> feat: add support for Soroban RPC server. [WIP]

- stellar_sdk/strkey.py
- tests/test_strkey.py
see https://github.com/stellar/stellar-protocol/pull/1324
> feat: add contract strkey support

- .github/workflows/continuous-integration-workflow.yml
see https://docs.pypi.org/trusted-publishers/
> ci: publishing to PyPI with a Trusted Publisher

- stellar_sdk/base_soroban_server.py
- stellar_sdk/soroban_rpc.py
- stellar_sdk/soroban_server.py
- stellar_sdk/soroban_server_async.py
- tests/test_soroban_server_async.py
- tests/test_soroban_server_sync.py
> feat: support resource leeway parameter when simulating Soroban transactions.

- CHANGELOG.md
- stellar_sdk/soroban_rpc.py
- tests/test_soroban_server_async.py
- tests/test_soroban_server_sync.py
> feat: Support for the new, optional `diagnostic_events_xdr` field on the `SorobanServer.send_transaction` method.

- CHANGELOG.md
- examples/payment.py
- examples/payment_async.py
- stellar_sdk/exceptions.py
- stellar_sdk/server.py
- stellar_sdk/server_async.py
- tests/test_server_async.py
- tests/test_server_sync.py
> feat: add support for Horizon's transactions_async API interfaces.

- docs/en/generate_keypair.rst
The sentence has a small mistake. "Vou" should be "You"
> Little grammatical error
