StellarCN/py-stellar-base

- stellar_base/asset.py
- stellar_base/horizon.py
- stellar_base/operation.py
- stellar_base/utils.py
Fixing SetOptions, the signer address and weight was expecting an unexisting object type, now two opts dict keys. Also doing some consistency cosmetic changes.
Adding a helper method to run queries on Horizon using the configured base url.
Adding a helper method to retrieve an Asset info as a dict.
XDR packing account object would fail if address is of type unicode.
> Some fixes and helpers.

- stellar_base/sample.py
- stellar_base/utils.py
And forgot to document that relative import doesn't work if repo is downloaded through `git` and not using `pip`. 
````
-from .stellarxdr import StellarXDR_pack as Xdr
+from stellar_base.stellarxdr import StellarXDR_pack as Xdr
````
> Improved sample

- tests/test_cases.py
Currently in Python2.7 and Python3.4 passes for
- CreateAccount
- Payment
- ChangeTrust
but errors for 
- PathPayment
- ManageOffer
- CreatePassiveOffer
- SetOptions. 
AllowTrust errors only in Python3.4. 
Ping to #15 and #17
> Add tests for every Op

- stellar_base/utils.py
- tests/test_utils.py
There were some problems with previous implementation of `best_rational_approximation`:
```python
def best_rational_approximation(x):
p = Fraction(x).limit_denominator(10**8)
return {'n': p.numerator,'d': p.denominator}
```
1. The value passed to `limit_denominator` was incorrect. The max value `Price.n` and `Price.d` can hold is `2147483647` ([check XDR](https://github.com/stellar/stellar-core/blob/master/src/xdr/Stellar-ledger-entries.x#L45-L49)).
2. The previous implementation was not limiting `numerator` value at all so it could cause passing some unexpected price to the ledger.
I ported the continued fraction algorithm we use in ruby, js and java libraries and added tests.
PS. The last time I wrote python code was a few years ago so let me know if I made any stupid error :smile:.
> Fix best_rational_approximation

- stellar_base/operation.py
- tests/test_envelope.py
- tests/test_horizon.py
This PR adds higher abstraction layer for amounts. After merging this PR, amounts will have to be strings representing amount in lumens:
```python
CreateAccount({
'destination': 'GCGA4XGBZJBM3YUY6W5GDFHHB2J4JHXX5WGG23TNPAOUDOBP2KSKKSPF',
'starting_balance': '20'
})
```
This was changed to:
* release developers from having to multiply all amounts by `10**7`,
* prevent rounding errors like:
```python
Payment({
'destination': self.dest,
'asset': Asset.native(),
'amount': 1.1+2.2 # 3.3000000000000003
})
```
> Amount abstraction layer

- stellar_base/asset.py
When making an order book request, the Asset type is a required parameter for both selling and buying Asset, so it would be easier to wrap the horizon order book parameters if the Asset object provides the type as a public attribute.
> moved asset type to be an attribute of Asset object

- stellar_base/builder.py
The correct key name is timeBounds.
Issue: #81
> builder: Fix XDR opts key name for time bounds.

- stellar_base/utils.py
The comparison was never triggered and the PreAuth signer was not added to XDR.
Issue: #82
> utils: Fix PreAuth signer in signer_key_xdr_object.

- stellar_base/operation.py
Path payments were not working at all, always throwing an exception
```
File "/home/jimbob/.virtualenvs/zed/lib/python3.5/site-packages/stellar_base/builder.py", line 307, in sign
self.te.sign(key_pair)
File "/home/jimbob/.virtualenvs/zed/lib/python3.5/site-packages/stellar_base/transaction_envelope.py", line 22, in sign
tx_hash = self.hash_meta()
File "/home/jimbob/.virtualenvs/zed/lib/python3.5/site-packages/stellar_base/transaction_envelope.py", line 41, in hash_meta
return xdr_hash(self.signature_base())
File "/home/jimbob/.virtualenvs/zed/lib/python3.5/site-packages/stellar_base/transaction_envelope.py", line 50, in signature_base
tx.pack_Transaction(self.tx.to_xdr_object())
File "/home/jimbob/.virtualenvs/zed/lib/python3.5/site-packages/stellar_base/stellarxdr/StellarXDR_pack.py", …
```
> Convert path assets to XDR objects

- stellar_base/operation.py
`builder.append_manage_data_op` not working when removing the data value.
> Fix ManageData defect when data_val is None(remove data)

- .codeclimate.yml
- stellar_base/operation.py
- stellar_base/stellarxdr/StellarXDR_pack.py
- stellar_base/transaction.py
- stellar_base/utils.py
- tests/test_operation.py
- tests/test_transaction.py
Hi again,
This PR mainly
- Refactored the operation construction from if ... else to subclass scan
- Removed some redundant assert (no need to assert isinstance dict if later a .get is called)
- Fixed some general error handling
By the way, it's really a good idea to change some dictionary argument like `opts` in `Transaction.__init__` to keyword arguments. Just it will introduce some breaking change, but it will be more user-friendly, what do you think ?
> refactor operation construction

- docs/install.rst
- examples/issue_asset.py
- examples/payment.py
- stellar_base/builder.py
- stellar_base/memo.py
- stellar_base/operation.py
- stellar_base/transaction_envelope.py
- stellar_base/utils.py
- tests/test_memo.py
Hash Memo, Return Hash Memo, PreAuthTx, hashX Signer accept 32 bytes hash or hex encoded string now.
Thanks to Areghan.
> Optimize the processing of hex and bytes hash

- stellar_base/address.py
- stellar_base/horizon.py
- tests/test_asset.py
I added the https://www.stellar.org/developers/horizon/reference/endpoints/trades-for-account.html endpoint. I included a test that i had with this padding removing i had the fix for that as well but it was already done in the meantime.
> Add missing endpoint

- examples/listen_payments.py
- stellar_base/horizon.py
drop "hello" and "byebye" messages, json.loads the normal messages when using sse=True
BREAKING CHANGE: The returned message type changed from str to dict
re #200
> perf: improve sse message

- Pipfile
- docs/en/api.rst
- docs/zh_CN/api.rst
- requirements-test.txt
- stellar_sdk/sep/exceptions.py
- stellar_sdk/server.py
- stellar_sdk/transaction.py
- tests/sep/test_account_memo_requirements.py
- tests/test_server.py
> feat: add support for SEP-0029.

- .gitignore
- stellar_sdk/client/aiohttp_client.py
- stellar_sdk/client/defines.py
- stellar_sdk/client/requests_client.py
- Using shorter default timeout for GET requests.
- Using Horizon submit transaction timeout with grace for POST requests.
> Separating GET and POST timeout values

- stellar_sdk/sep/stellar_web_authentication.py
- tests/sep/test_stellar_web_authentication.py
> fix: SEP-10, fails if a challenge for a nonexistent account has extra signatures

- stellar_sdk/sep/stellar_web_authentication.py
- tests/sep/test_stellar_web_authentication.py
resolve #421 
* Updates the SEP-10 utility function parameters to support [SEP-10 v3.1.0](https://github.com/stellar/stellar-protocol/commit/6c8c9cf6685c85509835188a136ffb8cd6b9c11c).
- The following functions add the `web_auth_domain` parameter:
- `stellar_sdk.sep.stellar_web_authentication.build_challenge_transaction()`
- `stellar_sdk.sep.stellar_web_authentication.read_challenge_transaction()`
- `stellar_sdk.sep.stellar_web_authentication.verify_challenge_transaction_signers()`
- `stellar_sdk.sep.stellar_web_authentication.verify_challenge_transaction_signed_by_client()`
- `stellar_sdk.sep.stellar_web_authentication.verify_challenge_transaction_signed_by_client_master_key()`
- `stellar_sdk.sep.stellar_web_authentication.verify_challenge_transaction_threshold()`
- …
> feat: add support for SEP-10 v3.1.0.

- stellar_sdk/client/aiohttp_client.py
> fix: throw stellar_sdk.exceptions.ConnectionError in AiohttpClient instead of the built-in ConnectionError.

- stellar_sdk/client/aiohttp_client.py
`asyncio.exceptions.TimeoutError` available in Python 3.8 and above
#448
> fix: make `AiohttpClient` compatible with Python 3.6 and 3.7

- stellar_sdk/sep/stellar_web_authentication.py
- tests/sep/test_stellar_web_authentication.py
Adds bare-bones SDK support for SEP-10 challenges including the experimental 'client_domain' Manage Data operation used for client attribution.
SEP-10 PR: stellar/stellar-protocol#760
The changes made here do not implement all verifications described in the protocol change linked above. The specific changes made are:
- `read_challenge_transaction()` accepts Manage Data operations with source accounts not equal to `server_account_id` if the data name of operation is `client_domain`.
- This differs from the current behavior, in which the function would raise an error if an additional operation did not have it's source account set to `server_account_id`
- `verify_challenge_transaction_signers()` verifies that the source account of the `client_domain` Manage Data operation signed the …
> SEP-10: added support for 'client_domain' ManageData operations in challenges (client attribution)

- stellar_sdk/xdr/claim_predicate.py
- tests/test_operation.py
See #464
`not_predicate` is optional, we did not notice this, which caused the SDK to fail to parse the `not_predicate` properly.
> fix: fix the problem that `not_predicate` cannot be parsed normally.

- stellar_sdk/fee_bump_transaction.py
- stellar_sdk/sep/stellar_web_authentication.py
- stellar_sdk/sep/txrep.py
- stellar_sdk/transaction.py
- stellar_sdk/transaction_builder.py
- tests/sep/test_stellar_web_authentication.py
- tests/test_fee_bump_transaction.py
- tests/test_transaction.py
resolve #433
One reason why we made this change is to make it consistent with `Operation.source`(#433). Another reason is that we are going to add support for SEP-23, so we need to add a new type - `MuxedAccount`, after this `str` will represent ed25519 public key, and `MuxedAccount` will represent muxed account. 
for example `Transaction.source`'s type will be `Union[str, MuxedAccount]`, when `Transaction.source` is `str`, it must be an ed25519 address starting with `G`.
> refactor: change the type of `FeeBumpTransaction.fee_source` and `Transaction.source` from `Keypair` to `str`

- stellar_sdk/client/aiohttp_client.py
> fix: AiohttpClient.__str__() references missing instance attribute self.pool_size

- stellar_sdk/sep/stellar_web_authentication.py
- tests/sep/test_stellar_web_authentication.py
Allows muxed accounts to be passed for `client_account_id` and adds a `memo` parameter to `ChallengeTransaction` and `build_challenge_transaction()`. These changes implement the specification's update for pooled/shared/omnibus account support: [#1036](https://github.com/stellar/stellar-protocol/pull/1036).
These changes should be backported to all major versions that have the `ChallengeTransaction` class.
> SEP-10: Add muxed account and memo support

- stellar_sdk/sep/stellar_web_authentication.py
- tests/sep/test_stellar_web_authentication.py
I missed another SEP-10 utility function, `verify_challenge_transaction()` that needed to be aware of muxed accounts. 
In Polaris, this function is specifically used when the Stellar account does not exist and therefore only the master signer of the account needs to have signed the challenge. The function needs to check if the `ChallengeTransaction.client_account_id` is a muxed address or not and adjust accordingly.
I believe this will warrant a patch release (4.2.1), sorry for missing this the first time.
> SEP-10: check for muxed accounts in `verify_challenge_transaction()`

- stellar_sdk/client/aiohttp_client.py
There are some endpoints where if the cursor is set to now the program will never receive new messages.
ex. https://horizon.stellar.org/accounts/{account_id}/offers
> refator: no longer sets "now" as the default cursor for AiohttpClient.stream

- stellar_sdk/base_server.py
- stellar_sdk/call_builder/base/base_strict_receive_paths_call_builder.py
- stellar_sdk/call_builder/base/base_strict_send_paths_call_builder.py
- stellar_sdk/call_builder/call_builder_async/strict_receive_paths_call_builder.py
- stellar_sdk/call_builder/call_builder_async/strict_send_paths_call_builder.py
- stellar_sdk/call_builder/call_builder_sync/strict_receive_paths_call_builder.py
- stellar_sdk/call_builder/call_builder_sync/strict_send_paths_call_builder.py
- stellar_sdk/sep/stellar_uri.py
- stellar_sdk/server.py
- stellar_sdk/server_async.py
- tests/call_builder/call_builder_async/test_strict_receive_paths_call_builder.py
- tests/call_builder/call_builder_async/test_strict_send_paths_call_builder.py
- tests/call_builder/call_builder_sync/test_strict_receive_paths_call_builder.py
- tests/call_builder/call_builder_sync/test_strict_send_paths_call_builder.py
- tests/sep/test_stellar_uri.py
- tests/test_server_async.py
- tests/test_server_sync.py
The following functions are affected:
- `PayStellarUri.__init__`
- `Server.strict_receive_paths`
- `Server.strict_send_paths`
- `AsyncServer.strict_receive_paths`
- `AsyncServer.strict_send_paths`
#596 
#594
> fix: make some amount fields accept Decimal.

- stellar_sdk/client/requests_client.py
`DEFAULT_POST_TIMEOUT_SECONDS` and _`HORIZON_SUBMIT_TRANSACTION_API_TIMEOUT_SECONDS` is set to around 30 seconds and default number of retries is 3, when sending  post requests it may can take 4*30 seconds and result in scenarios, where client is waiting for a long time, just to get tx_too_late error.
> Clarify timeout in arg comments

- stellar_sdk/soroban/types/enum.py
Got this error when creating an instance of `soroban.types.enum.Enum`:
```
File "/home/project/script.py", line 195, in build_enum
return Enum("custom", Symbol(v1))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/project/.venv/lib/python3.11/site-packages/stellar_sdk/soroban/types/enum.py", line 22, in __init__
if self.value is not None:
^^^^^^^^^^
AttributeError: 'Enum' object has no attribute 'value'
```
I'm guessing that removing the `self.` is the correct solution.
> Fixed Soroban enum self.value

- stellar_sdk/transaction_builder.py
> refactor: make the `parameters` parameter in `TransactionBuilder.append_invoke_contract_function_op` optional.

- stellar_sdk/scval.py
- tests/test_scval.py
> improve: sort the dictionary based on the key when calling `scval.to_struct`.

- CHANGELOG.md
- stellar_sdk/soroban_rpc.py
- tests/test_soroban_server_async.py
- tests/test_soroban_server_sync.py
> feat: add support for Soroban-RPC 21

- stellar_sdk/address.py
Allow importing from the main package:
`from stellar_sdk import AddressType`
> feat: Expose AddressType for easy importing

- .github/workflows/continuous-integration-workflow.yml
- CHANGELOG.md
- examples/send_asset_to_contract_without_rpc.py
- stellar_sdk/transaction_builder.py
- tests/integration_utils.py
- tests/test_transaction_builder.py
Send:
```python
from stellar_sdk import *
server_url = "https://horizon.stellar.org"
network_passphrase = Network.PUBLIC_NETWORK_PASSPHRASE
alice_kp = Keypair.from_mnemonic_phrase("")
server = Server(server_url)
source_account = server.load_account(alice_kp.public_key)
tx = TransactionBuilder(source_account, network_passphrase=network_passphrase).append_payment_to_contract_op(
"CASURCIREQG46FT3B7TFRIEETDUIAYRTCEZL4EWBEAJVX77CWPAQWD6R",
asset=Asset.native(),
amount="0.0001",
).set_timeout(300).build()
tx.sign(alice_kp)
print(tx.to_xdr())
resp = server.submit_transaction(tx)
print(resp)
```
Restore:
```python
from stellar_sdk import *
server_url = "https://horizon.stellar.org"
network_passphrase = Network.PUBLIC_NETWORK_PASSPHRASE
alice_kp = Keypair.from_mnemonic_phrase()
server = …
```
> feat: add functions to send assets to contract address without relying on Stellar RPC.

- pyproject.toml
- stellar_sdk/sep/stellar_toml.py
- uv.lock
https://docs.python.org/3/library/tomllib.html
> refactor: use `tomllib` instead of `toml` library in Python 3.11 and above.

- stellar_sdk/soroban_rpc.py
- stellar_sdk/soroban_server.py
- stellar_sdk/soroban_server_async.py
- tests/test_soroban_server_async.py
- tests/test_soroban_server_sync.py
From the official API reference:
`endLedger` - Ledger sequence number represents the end of search window (exclusive). If a cursor is included in the request, endLedger must be omitted.
> feat: `getEvents` RPC method - expose `endLedger` param
